### ISSUE TITLE
No content is loading on a lot of sites

### ISSUE THREAD

**Issue by johngruen** [mozilla/side-view#85]
Seeing this on a lot of sites: `www.nytimes.com`, `trello.com` `calendar.google.com` don't show up

![screen shot 2018-03-15 at 1 31 44 pm](https://user-images.githubusercontent.com/3323249/37483992-3cde0276-2855-11e8-90ec-b92fd1feee6d.png)

**Comment by ianb** [comment]
I'm not able to reproduce this. Are you on the latest Nightly? #80 could be related, and has been fixed in the last day or two.

**Comment by johngruen** [comment]
I feel like i may have gotten my profile in a bad state here...i'll noodle around a bit

**Comment by johngruen** [comment]
Yeah, something was up with my inspector. iframes are there but there seems to be CSP issues with just a ton of sites.

**Comment by fzzzy** [comment]
I tested nytimes.com, trello.com, and calendar.google.com and they all show up now. Open new issues for any sites you still encounter problems with.
